name: Progress Tracker

on:
  issues:
    types: [closed, opened, reopened]
  pull_request:
    types: [closed, merged]
  schedule:
    # Daily progress snapshot at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  update-progress:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install PyYAML requests
          
      - name: Update progress metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/update-progress.py
          
      - name: Commit progress update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add context/TopicTracker/progress.yaml
          git diff --quiet && git diff --staged --quiet || \
            git commit -m "chore: Update progress tracker [skip ci]"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Generate progress report
        if: github.event_name == 'schedule'
        run: |
          python scripts/generate-progress-report.py > progress-report.md
          
      - name: Post progress to discussions
        if: github.event_name == 'schedule'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: 1  # Assuming issue #1 is the progress tracking issue
          body-path: progress-report.md